export function initUI() {
    return {
        periodEl: document.getElementById('period'),
        periodControlEl: document.querySelector('.period-control'),
        periodValueEl: document.getElementById('period-value'),
        lengthEl: document.getElementById('length'),
        ratioEl: document.getElementById('ratio'),
        chartTitleEl: document.getElementById('chart-title'),
        metaLineEl: document.getElementById('meta-line'),
        chartStatusEl: document.getElementById('chart-status'),
        sensorSummaryEl: document.getElementById('sensor-summary'),
        deviceStatusEl: document.querySelector('.device-status'),
        lastUpdatedEl: document.getElementById('last-updated'),
        dataStateDotEl: document.getElementById('data-state-dot'),
        dataStateTextEl: document.getElementById('data-state-text'),
        refreshBtn: document.getElementById('refresh'),
        downloadBtn: document.getElementById('download'),
        chartFullscreenBtn: document.getElementById('chart-fullscreen'),
        chartCanvasEl: document.getElementById('chart'),
        chartCardEl: document.querySelector('.chart-card'),
        chartMiniLegendEl: document.getElementById('chart-mini-legend'),
        loadingOverlayEl: document.getElementById('loading-overlay'),
        loadingTextEl: document.getElementById('loading-text'),
        settingsBtn: document.getElementById('settings-btn'),
        authModalEl: document.getElementById('auth-modal'),
        authFormEl: document.getElementById('auth-form'),
        authLoginEl: document.getElementById('auth-login'),
        authPasswordEl: document.getElementById('auth-password'),
        authErrorEl: document.getElementById('auth-error'),
        authSubmitEl: document.getElementById('auth-submit'),
    };
}
